replicaCount: 2

image:
  repository: amadidominic15/web-app
  pullPolicy: IfNotPresent
  tag: "15502496472"

ingress:
  enabled: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  protocol: TCP