replicaCount: 2

image:
  repository: amadidominic15/web-app
  pullPolicy: IfNotPresent
  tag: "18818179137"

ingress:
  enabled: true
  className: nginx

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  protocol: TCP